// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/git-obj.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GitSignature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitSignature) Reset()         { *m = GitSignature{} }
func (m *GitSignature) String() string { return proto.CompactTextString(m) }
func (*GitSignature) ProtoMessage()    {}
func (*GitSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4ecdf46c712e4c3, []int{0}
}

func (m *GitSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitSignature.Unmarshal(m, b)
}
func (m *GitSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitSignature.Marshal(b, m, deterministic)
}
func (m *GitSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitSignature.Merge(m, src)
}
func (m *GitSignature) XXX_Size() int {
	return xxx_messageInfo_GitSignature.Size(m)
}
func (m *GitSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_GitSignature.DiscardUnknown(m)
}

var xxx_messageInfo_GitSignature proto.InternalMessageInfo

func (m *GitSignature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitSignature) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GitSignature) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type GitCommit struct {
	ParentId             []string      `protobuf:"bytes,1,rep,name=ParentId,proto3" json:"ParentId,omitempty"`
	Author               *GitSignature `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Committer            *GitSignature `protobuf:"bytes,3,opt,name=Committer,proto3" json:"Committer,omitempty"`
	Message              string        `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	TreeId               string        `protobuf:"bytes,5,opt,name=TreeId,proto3" json:"TreeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GitCommit) Reset()         { *m = GitCommit{} }
func (m *GitCommit) String() string { return proto.CompactTextString(m) }
func (*GitCommit) ProtoMessage()    {}
func (*GitCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4ecdf46c712e4c3, []int{1}
}

func (m *GitCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitCommit.Unmarshal(m, b)
}
func (m *GitCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitCommit.Marshal(b, m, deterministic)
}
func (m *GitCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitCommit.Merge(m, src)
}
func (m *GitCommit) XXX_Size() int {
	return xxx_messageInfo_GitCommit.Size(m)
}
func (m *GitCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_GitCommit.DiscardUnknown(m)
}

var xxx_messageInfo_GitCommit proto.InternalMessageInfo

func (m *GitCommit) GetParentId() []string {
	if m != nil {
		return m.ParentId
	}
	return nil
}

func (m *GitCommit) GetAuthor() *GitSignature {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *GitCommit) GetCommitter() *GitSignature {
	if m != nil {
		return m.Committer
	}
	return nil
}

func (m *GitCommit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GitCommit) GetTreeId() string {
	if m != nil {
		return m.TreeId
	}
	return ""
}

func init() {
	proto.RegisterType((*GitSignature)(nil), "proto.GitSignature")
	proto.RegisterType((*GitCommit)(nil), "proto.GitCommit")
}

func init() { proto.RegisterFile("src/proto/git-obj.proto", fileDescriptor_f4ecdf46c712e4c3) }

var fileDescriptor_f4ecdf46c712e4c3 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x89, 0x33, 0xad, 0xe6, 0xea, 0xea, 0x2a, 0x1a, 0x5c, 0x0d, 0xb3, 0x1a, 0x10, 0x67,
	0x50, 0x9f, 0x40, 0x44, 0x86, 0x82, 0x8a, 0xd4, 0xbe, 0x40, 0x6a, 0x2f, 0x35, 0x62, 0x1a, 0x49,
	0x6f, 0x1f, 0xce, 0xb7, 0x93, 0xde, 0xd4, 0x9f, 0xcd, 0xac, 0x72, 0xbe, 0xe4, 0xe3, 0xe4, 0xc0,
	0x59, 0x1f, 0x5f, 0x37, 0x9f, 0x31, 0x70, 0xd8, 0xb4, 0x8e, 0x2f, 0x43, 0xfd, 0xbe, 0x16, 0xc2,
	0x4c, 0x8e, 0xe5, 0x03, 0x1c, 0x6d, 0x1d, 0xbf, 0xb8, 0xb6, 0xb3, 0x3c, 0x44, 0x42, 0x84, 0xf9,
	0x93, 0xf5, 0x64, 0xd4, 0x42, 0xad, 0x74, 0x29, 0x19, 0x4f, 0x20, 0xbb, 0xf7, 0xd6, 0x7d, 0x98,
	0x3d, 0xb9, 0x4c, 0x30, 0x9a, 0x95, 0xf3, 0x64, 0x66, 0xc9, 0x1c, 0xf3, 0xf2, 0x4b, 0x81, 0xde,
	0x3a, 0xbe, 0x0b, 0xde, 0x3b, 0xc6, 0x73, 0x38, 0x78, 0xb6, 0x91, 0x3a, 0x2e, 0x1a, 0xa3, 0x16,
	0xb3, 0x95, 0x2e, 0x7f, 0x19, 0x2f, 0x20, 0xbf, 0x1d, 0xf8, 0x2d, 0x44, 0x29, 0x3d, 0xbc, 0x3e,
	0x4e, 0xb3, 0xd6, 0xff, 0xc7, 0x94, 0x93, 0x82, 0x57, 0xa0, 0x53, 0x25, 0x53, 0x94, 0xff, 0x76,
	0xf8, 0x7f, 0x16, 0x1a, 0xd8, 0x7f, 0xa4, 0xbe, 0xb7, 0x2d, 0x99, 0xb9, 0x0c, 0xfc, 0x41, 0x3c,
	0x85, 0xbc, 0x8a, 0x44, 0x45, 0x63, 0x32, 0x79, 0x98, 0xa8, 0xce, 0xa5, 0xf0, 0xe6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0x12, 0xe2, 0xd7, 0x32, 0x01, 0x00, 0x00,
}
