// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/repo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Descript             string   `protobuf:"bytes,3,opt,name=Descript,proto3" json:"Descript,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{0}
}

func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (m *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(m, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Repo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repo) GetDescript() string {
	if m != nil {
		return m.Descript
	}
	return ""
}

type UserRepos struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Repos                []*Repo  `protobuf:"bytes,2,rep,name=Repos,proto3" json:"Repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRepos) Reset()         { *m = UserRepos{} }
func (m *UserRepos) String() string { return proto.CompactTextString(m) }
func (*UserRepos) ProtoMessage()    {}
func (*UserRepos) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{1}
}

func (m *UserRepos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRepos.Unmarshal(m, b)
}
func (m *UserRepos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRepos.Marshal(b, m, deterministic)
}
func (m *UserRepos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRepos.Merge(m, src)
}
func (m *UserRepos) XXX_Size() int {
	return xxx_messageInfo_UserRepos.Size(m)
}
func (m *UserRepos) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRepos.DiscardUnknown(m)
}

var xxx_messageInfo_UserRepos proto.InternalMessageInfo

func (m *UserRepos) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRepos) GetRepos() []*Repo {
	if m != nil {
		return m.Repos
	}
	return nil
}

func init() {
	proto.RegisterType((*Repo)(nil), "proto.Repo")
	proto.RegisterType((*UserRepos)(nil), "proto.UserRepos")
}

func init() { proto.RegisterFile("src/proto/repo.proto", fileDescriptor_678120916375f536) }

var fileDescriptor_678120916375f536 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4a, 0x2d, 0xc8, 0xd7, 0x03, 0x33, 0x85, 0x58, 0xc1,
	0x94, 0x92, 0x1b, 0x17, 0x4b, 0x50, 0x6a, 0x41, 0xbe, 0x10, 0x1f, 0x17, 0x93, 0x67, 0x8a, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x93, 0x67, 0x8a, 0x90, 0x10, 0x17, 0x8b, 0x5f, 0x62, 0x6e,
	0xaa, 0x04, 0x13, 0x58, 0x04, 0xcc, 0x16, 0x92, 0xe2, 0xe2, 0x70, 0x49, 0x2d, 0x4e, 0x2e, 0xca,
	0x2c, 0x28, 0x91, 0x60, 0x06, 0x8b, 0xc3, 0xf9, 0x4a, 0x6e, 0x5c, 0x9c, 0xa1, 0xc5, 0xa9, 0x45,
	0x20, 0xb3, 0x8a, 0x85, 0xc4, 0xb8, 0xd8, 0x40, 0x1c, 0xb8, 0x81, 0x50, 0x9e, 0x90, 0x22, 0x17,
	0x2b, 0x58, 0x81, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x37, 0xc4, 0x29, 0x7a, 0x20, 0xb1,
	0x20, 0x88, 0x4c, 0x12, 0x1b, 0x58, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xdc, 0x52,
	0x37, 0xb5, 0x00, 0x00, 0x00,
}
