// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/repo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Descript             string   `protobuf:"bytes,3,opt,name=Descript,proto3" json:"Descript,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{0}
}

func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (m *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(m, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Repo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repo) GetDescript() string {
	if m != nil {
		return m.Descript
	}
	return ""
}

type UserRepos struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Repos                []*Repo  `protobuf:"bytes,2,rep,name=Repos,proto3" json:"Repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRepos) Reset()         { *m = UserRepos{} }
func (m *UserRepos) String() string { return proto.CompactTextString(m) }
func (*UserRepos) ProtoMessage()    {}
func (*UserRepos) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{1}
}

func (m *UserRepos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRepos.Unmarshal(m, b)
}
func (m *UserRepos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRepos.Marshal(b, m, deterministic)
}
func (m *UserRepos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRepos.Merge(m, src)
}
func (m *UserRepos) XXX_Size() int {
	return xxx_messageInfo_UserRepos.Size(m)
}
func (m *UserRepos) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRepos.DiscardUnknown(m)
}

var xxx_messageInfo_UserRepos proto.InternalMessageInfo

func (m *UserRepos) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRepos) GetRepos() []*Repo {
	if m != nil {
		return m.Repos
	}
	return nil
}

type RepoRef struct {
	TargetId             string   `protobuf:"bytes,1,opt,name=TargetId,proto3" json:"TargetId,omitempty"`
	IsBranch             bool     `protobuf:"varint,2,opt,name=IsBranch,proto3" json:"IsBranch,omitempty"`
	IsNote               bool     `protobuf:"varint,3,opt,name=IsNote,proto3" json:"IsNote,omitempty"`
	IsRemote             bool     `protobuf:"varint,4,opt,name=IsRemote,proto3" json:"IsRemote,omitempty"`
	IsTag                bool     `protobuf:"varint,5,opt,name=IsTag,proto3" json:"IsTag,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepoRef) Reset()         { *m = RepoRef{} }
func (m *RepoRef) String() string { return proto.CompactTextString(m) }
func (*RepoRef) ProtoMessage()    {}
func (*RepoRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{2}
}

func (m *RepoRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepoRef.Unmarshal(m, b)
}
func (m *RepoRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepoRef.Marshal(b, m, deterministic)
}
func (m *RepoRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepoRef.Merge(m, src)
}
func (m *RepoRef) XXX_Size() int {
	return xxx_messageInfo_RepoRef.Size(m)
}
func (m *RepoRef) XXX_DiscardUnknown() {
	xxx_messageInfo_RepoRef.DiscardUnknown(m)
}

var xxx_messageInfo_RepoRef proto.InternalMessageInfo

func (m *RepoRef) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *RepoRef) GetIsBranch() bool {
	if m != nil {
		return m.IsBranch
	}
	return false
}

func (m *RepoRef) GetIsNote() bool {
	if m != nil {
		return m.IsNote
	}
	return false
}

func (m *RepoRef) GetIsRemote() bool {
	if m != nil {
		return m.IsRemote
	}
	return false
}

func (m *RepoRef) GetIsTag() bool {
	if m != nil {
		return m.IsTag
	}
	return false
}

func (m *RepoRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RepoRefs struct {
	Repo                 *Repo      `protobuf:"bytes,1,opt,name=Repo,proto3" json:"Repo,omitempty"`
	Refs                 []*RepoRef `protobuf:"bytes,2,rep,name=Refs,proto3" json:"Refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RepoRefs) Reset()         { *m = RepoRefs{} }
func (m *RepoRefs) String() string { return proto.CompactTextString(m) }
func (*RepoRefs) ProtoMessage()    {}
func (*RepoRefs) Descriptor() ([]byte, []int) {
	return fileDescriptor_678120916375f536, []int{3}
}

func (m *RepoRefs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepoRefs.Unmarshal(m, b)
}
func (m *RepoRefs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepoRefs.Marshal(b, m, deterministic)
}
func (m *RepoRefs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepoRefs.Merge(m, src)
}
func (m *RepoRefs) XXX_Size() int {
	return xxx_messageInfo_RepoRefs.Size(m)
}
func (m *RepoRefs) XXX_DiscardUnknown() {
	xxx_messageInfo_RepoRefs.DiscardUnknown(m)
}

var xxx_messageInfo_RepoRefs proto.InternalMessageInfo

func (m *RepoRefs) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *RepoRefs) GetRefs() []*RepoRef {
	if m != nil {
		return m.Refs
	}
	return nil
}

func init() {
	proto.RegisterType((*Repo)(nil), "proto.Repo")
	proto.RegisterType((*UserRepos)(nil), "proto.UserRepos")
	proto.RegisterType((*RepoRef)(nil), "proto.RepoRef")
	proto.RegisterType((*RepoRefs)(nil), "proto.RepoRefs")
}

func init() { proto.RegisterFile("src/proto/repo.proto", fileDescriptor_678120916375f536) }

var fileDescriptor_678120916375f536 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0xd5, 0xae, 0x2d, 0x9d, 0x27, 0xed, 0x60, 0x4d, 0x28, 0xe2, 0xc2, 0xc8, 0x69, 0xa7,
	0x4d, 0x82, 0x37, 0x40, 0x68, 0x52, 0x2e, 0x43, 0x8a, 0xc6, 0x03, 0x94, 0xce, 0x1d, 0x1c, 0x46,
	0xaa, 0x24, 0xef, 0xc3, 0xab, 0x22, 0x3b, 0x5d, 0x40, 0x9c, 0x92, 0xcf, 0xbf, 0xe3, 0xfc, 0xfe,
	0x61, 0x15, 0x7c, 0xbf, 0x1b, 0xbd, 0x8b, 0x6e, 0xe7, 0x69, 0x74, 0x5b, 0xb9, 0x62, 0x2d, 0x87,
	0xde, 0x43, 0x65, 0x69, 0x74, 0xb8, 0x84, 0xd2, 0x9c, 0x54, 0xb1, 0x2e, 0x36, 0x73, 0x5b, 0x9a,
	0x13, 0x22, 0x54, 0x87, 0xee, 0x42, 0xaa, 0x94, 0x8a, 0xdc, 0xf1, 0x0e, 0xda, 0x17, 0x0a, 0xbd,
	0xff, 0x1c, 0xa3, 0x9a, 0x49, 0x3d, 0xb3, 0xde, 0xc3, 0xfc, 0x2d, 0x90, 0xe7, 0x59, 0x01, 0x6f,
	0xa1, 0x61, 0xc8, 0x03, 0x27, 0xc2, 0x07, 0xa8, 0xa5, 0x41, 0x95, 0xeb, 0xd9, 0x66, 0xf1, 0xb8,
	0x48, 0x56, 0xb6, 0x5c, 0xb3, 0x49, 0xd1, 0xdf, 0x05, 0xdc, 0x08, 0xd3, 0xc0, 0xff, 0x1d, 0x3b,
	0x7f, 0xa6, 0x98, 0x07, 0x65, 0x66, 0xcd, 0x84, 0x67, 0xdf, 0x7d, 0xf5, 0x1f, 0xe2, 0xb1, 0xb5,
	0x99, 0xf9, 0x7b, 0x13, 0x0e, 0x2e, 0x92, 0xb8, 0x6c, 0xed, 0x44, 0xe9, 0x8d, 0xa5, 0x0b, 0x2b,
	0xd5, 0xf5, 0x4d, 0x62, 0x5c, 0x41, 0x6d, 0xc2, 0xb1, 0x3b, 0xab, 0x5a, 0x84, 0x04, 0x39, 0x85,
	0xe6, 0x37, 0x05, 0xfd, 0x0a, 0xed, 0x64, 0x30, 0xe0, 0x7d, 0x4a, 0x4f, 0xdc, 0xfd, 0xdb, 0x27,
	0xc5, 0xaa, 0xb9, 0x61, 0xb8, 0x2e, 0xbc, 0xfc, 0xdb, 0x40, 0x83, 0x15, 0xed, 0xbd, 0x91, 0xe2,
	0xd3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x0a, 0xc9, 0x9b, 0xa8, 0x01, 0x00, 0x00,
}
